### ISSUE TITLE
service fails behind proxy

### ISSUE THREAD

**Issue by computersalat** [openSUSE/obs-service-github_tarballs#6]
`urllib` seems to have problems with no_proxy when talking to `local github`, but seems to be fine with `external_github` through proxy ...
... hence switch to `urllib2` at least

**Comment by seife** [comment]
more context:
   * internal OBS instance
   * internal github instance
   * https_proxy=http://proxy.corp:8080/
   * no_proxy="....,github.corp"
   * github_tarballs works for github.com
   * github_tarballs does not work for github.corp
   * I debugged this with trivial python urllib fetcher script and found, that no_proxy with urllib is not working, at least for https
   * switching to urllib2 fixes the problem
